[IDDS-517] final bill total cost page update (#172)
* add variant total cost page for handling final bill claims

* delete unused total cost adaptor/router

* tidy up conditional logic

* move errors to constants

* rename total claim router/adaptor/validator to total claim cost

* run lint fix

* add csrf protection middleware

* move setupCsrf before post routes in app

* run lint fix

* comment out jobs connecting to docker Inquests API container (not in use)

* move setupCsrf call back as csrf token not being parsed in form upload

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -222,17 +222,17 @@ jobs:
           AUTH_CLIENT_ID: ${{ secrets.E2E_AUTH_CLIENT_ID }}
           AUTH_CLIENT_SECRET: ${{ secrets.E2E_AUTH_CLIENT_SECRET }}
           INQUESTS_API_CLIENT_ID: ${{ secrets.E2E_INQUESTS_API_CLIENT_ID }}
-          E2E_PROVIDER_USERNAME: ${{ secrets.E2E_PROVIDER_USERNAME }}
-          E2E_PROVIDER_PASSWORD: ${{ secrets.E2E_PROVIDER_PASSWORD }}
-          E2E_PROVIDER_MFA_TOTP_SECRET: ${{ secrets.E2E_PROVIDER_MFA_TOTP_SECRET }}
+          # E2E_PROVIDER_USERNAME: ${{ secrets.E2E_PROVIDER_USERNAME }}
+          # E2E_PROVIDER_PASSWORD: ${{ secrets.E2E_PROVIDER_PASSWORD }}
+          # E2E_PROVIDER_MFA_TOTP_SECRET: ${{ secrets.E2E_PROVIDER_MFA_TOTP_SECRET }}
 
-      - name: Show API logs on failure
-        if: failure()
-        run: docker logs inquests-api
+      # - name: Show API logs on failure
+      #   if: failure()
+      #   run: docker logs inquests-api
 
-      - name: Stop API container
-        if: always()
-        run: docker rm -f inquests-api || true
+      # - name: Stop API container
+      #   if: always()
+      #   run: docker rm -f inquests-api || true
 
       - name: Upload trace artifacts
         if: always()
